import { Services } from "@/types";

export const SERVICES: Services[] = [
    {
        id: 1,
        imgSrc: "/images/service-icons/service-icon-1.webp",
        name: "Dental Checkup",
        text: "Routine examination and cleaning to maintain healthy teeth and gums.",
        href: "/#dental-checkup",
        idStr: "dental-checkup",
    },
    {
        id: 2,
        imgSrc: "/images/service-icons/service-icon-2.webp",
        name: "RVG X-RAY",
        text: "Digital X-ray technology providing instant, high-resolution images with 80% less radiation than traditional film.",
        href: "/#x-ray",
        idStr: "x-ray",
    },
    {
        id: 4,
        imgSrc: "/images/service-icons/service-icon-4.webp",
        name: "Gingivitis Periodontitis",
        text: "Specialized treatment for gum disease to restore healthy gums and prevent tooth loss.",
        href: "/#gingivitis-periodontitis",
        idStr: "gingivitis-periodontitis",
    },
    {
        id: 5,
        imgSrc: "/images/service-icons/service-icon-5.webp",
        name: "Composite and GIC Restoration",
        text: "Tooth-colored fillings to repair cavities and restore natural appearance.",
        href: "/#composite-and-gic-restoration",
        idStr: "composite-and-gic-restoration",
    },
    {
        id: 6,
        imgSrc: "/images/service-icons/service-icon-6.webp",
        name: "RCT",
        text: "Root canal treatment to save infected teeth and eliminate pain.",
        href: "/#rct",
        idStr: "rct",
    },
    {
        id: 7,
        imgSrc: "/images/service-icons/service-icon-7.webp",
        name: "Oral Surgery",
        text: "Surgical procedures for tooth extraction and complex dental treatments.",
        href: "/#oral-surgery",
        idStr: "oral-surgery",
    },
    {
        id: 8,
        imgSrc: "/images/service-icons/service-icon-8.webp",
        name: "CD, RPD",
        text: "Custom dentures and bridges to replace missing teeth and restore function.",
        href: "/#cd-rpd",
        idStr: "cd-rpd",
    },
    {
        id: 9,
        imgSrc: "/images/service-icons/service-icon-9.webp",
        name: "Extraction",
        text: "Safe tooth removal procedures for damaged or problematic teeth.",
        href: "/#extraction",
        idStr: "extraction",
    },
    {
        id: 10,
        imgSrc: "/images/service-icons/service-icon-10.webp",
        name: "Orthodontic Treatment",
        text: "Braces and aligners to straighten teeth and correct bite alignment.",
        href: "/#orthodontic-treatment",
        idStr: "orthodontic-treatment",
    },
    {
        id: 11,
        imgSrc: "/images/service-icons/service-icon-11.webp",
        name: "Dental Crown",
        text: "Custom caps to protect and restore damaged or weakened teeth.",
        href: "/#dental-crown",
        idStr: "dental-crown",
    },
    {
        id: 14,
        imgSrc: "/images/service-icons/service-icon-14.webp",
        name: "Scaling",
        text: "Professional plaque and tartar removal to maintain healthy gums and teeth.",
        href: "/#scaling",
        idStr: "scaling",
    },
    {
        id: 19,
        imgSrc: "/images/service-icons/service-icon-19.webp",
        name: "Flouride Application",
        text: "Professional treatment to strengthen tooth enamel and prevent cavities effectively.",
        href: "/#flouride-application",
        idStr: "flouride-application",
    },
    {
        id: 20,
        imgSrc: "/images/service-icons/service-icon-6.webp",
        name: "Pulpectomy/Pulpotomy",
        text: "Root canal treatment to save infected teeth and restore healthy function",
        href: "/#pulpectomy",
        idStr: "pulpectomy",
    },
    {
        id: 23,
        imgSrc: "/images/service-icons/service-icon-9.webp",
        name: "Surgical Extraction",
        text: "Advanced removal of complex or impacted teeth with specialized techniques.",
        href: "/#surgical-extraction",
        idStr: "surgical-extraction",
    },
    {
        id: 24,
        imgSrc: "/images/service-icons/service-icon-24.webp",
        name: "Temporary Filling",
        text: "Interim tooth protection to seal cavities and prevent sensitivity until permanent treatment.",
        href: "/#temporary-filling",
        idStr: "temporary-filling",
    },
    {
        id: 25,
        imgSrc: "/images/service-icons/service-icon-25.webp",
        name: "Miracle Mix",
        text: "Metal-reinforced glass ionomer material for durable crown build-ups and transitional restorations.",
        href: "/#miracle-mix",
        idStr: "miracle-mix",
    },
    {
        id: 26,
        imgSrc: "/images/service-icons/service-icon-26.webp",
        name: "Composite Veneering",
        text: "Tooth-colored resin layering to correct imperfections and create a natural, beautiful smile.",
        href: "/#composite-veneering",
        idStr: "composite-veneering",
    },
    {
        id: 27,
        imgSrc: "/images/service-icons/service-icon-27.webp",
        name: "Post & Core",
        text: "Metal or fiber post anchored in root canal to rebuild and strengthen severely damaged teeth.",
        href: "/#post-and-core",
        idStr: "post-and-core",
    },
    {
        id: 28,
        imgSrc: "/images/service-icons/service-icon-28.webp",
        name: "Flexible CD",
        text: "Comfortable, lightweight removable denture made from flexible material for natural appearance and fit.",
        href: "/#flexible-cd",
        idStr: "flexible-cd",
    },
    {
        id: 29,
        imgSrc: "/images/service-icons/service-icon-29.webp",
        name: "Space Maintainer",
        text: "Device that holds space for permanent teeth after premature loss of baby teeth.",
        href: "/#space-maintainer",
        idStr: "space-maintainer",
    },
    {
        id: 30,
        imgSrc: "/images/service-icons/service-icon-30.webp",
        name: "Splitting",
        text: "Stabilizing loose or mobile teeth by bonding them together for support and strength.",
        href: "/#splitting",
        idStr: "splitting",
    },
    {
        id: 31,
        imgSrc: "/images/service-icons/service-icon-31.webp",
        name: "Obturator",
        text: "Prosthetic device that closes openings in the palate to restore speech and swallowing.",
        href: "/#obturator",
        idStr: "obturator",
    },
    {
        id: 32,
        imgSrc: "/images/service-icons/service-icon-32.webp",
        name: "Tooth grinding",
        text: "Treatment for teeth grinding and clenching using protective guards and therapy methods.",
        href: "/#tooth-grinding",
        idStr: "tooth-grinding",
    },
    {
        id: 33,
        imgSrc: "/images/service-icons/service-icon-33.webp",
        name: "Operculectomy",
        text: "Surgical removal of gum tissue covering a partially erupted tooth to prevent infection.",
        href: "/#operculectomy",
        idStr: "operculectomy",
    },
    {
        id: 34,
        imgSrc: "/images/service-icons/service-icon-34.webp",
        name: "Apicetomny",
        text: "Surgical removal of tooth root tip and infected tissue when root canal fails.",
        href: "/#apicetomy",
        idStr: "apicetomy",
    },
    {
        id: 35,
        imgSrc: "/images/service-icons/service-icon-35.webp",
        name: "Cyst Enucieation",
        text: "Surgical removal of cysts from jaw or oral tissues to prevent recurrence and infection.",
        href: "/#cyst-enucieation",
        idStr: "cyst-enucieation",
    },
    {
        id: 36,
        imgSrc: "/images/service-icons/service-icon-36.webp",
        name: "Biopsy",
        text: "Tissue sample removal from oral lesions for laboratory analysis and diagnosis purposes.",
        href: "/#biopsy",
        idStr: "biopsy",
    },
    {
        id: 37,
        imgSrc: "/images/service-icons/service-icon-37.webp",
        name: "OSMF Management",
        text: "Treatment for oral submucous fibrosis using injections, therapy, and lifestyle modifications.",
        href: "/#osmf-management",
        idStr: "osmf-management",
    },
    {
        id: 38,
        imgSrc: "/images/service-icons/service-icon-38.webp",
        name: "Incision & Drainage",
        text: "Surgical opening and draining of abscesses to relieve pain and remove infected fluid.",
        href: "/#incision-and-drainage",
        idStr: "incision-and-drainage",
    },
];